### ISSUE TITLE
Tasks for next 2 weeks

### ISSUE THREAD

**Issue by sarthakkapila** [CheddarHQ/Cheddar#34]
### 📝 **WORK**  
We have exams from 11th and have 5 weeks for completing the project -1 week for presentation and final touches(recommended by superteam) -1 for exams so we have like 3 weeks in total, we need to E/acc lil bros

---

### 📋 **NEXT 2 WEEKS (arranged according to priority)**  
---
### 🔢 **Task List**
- [x] Task 1: *Attach API to graphs*

- [x] Task 2: *Separate all the components*
- *Description*: Gotta separate all components from the main page creating a lot of problems while gptying stuff and also remove useless code.

- [x] Task 3: *Add state management*
- *Description for task 3*: We have to manage state for stuff like output mint, user's address, amount slippage(connected to task 3)
<img width="804" alt="Screenshot 2024-09-05 at 2 59 30 PM" src="https://github.com/user-attachments/assets/c6c13455-7f38-42b7-ab48-94d4e623098d">
mainly we need to manage states for all the things cryptograph and crypto.

- [ ] #38

- [x] #37

- [x] #36

- [ ] #39
- *Description for task 7*: Literally every page and tab we reopen requests for data which is quite inefficient, some of the data needs to re rendered like price of the coin when we click on the coin but most of it is wasting api requests we need to fix it!

- [x] #40
- *Description for task 7*: add d1 database for all the stuff we need to store

- [x] #44
- *Description for task 9*: Gotta add a userprofile of every user that we can visit and also deploy it on the web with a unique link linked to cloudflare D1 task, the profile on app will contain stuff like the user's activity like coins bought twitter link etc etc.

- [ ] Task 10: *Add features like top coins of the day*
<img width="1275" alt="Screenshot 2024-09-05 at 3 20 09 PM" src="https://github.com/user-attachments/assets/3f3a7f66-7468-4c42-8e09-fd0326058fc6">

- [x] Task 11: *Make solana specific*
- *Description for task 11*: Right now the coins trade/graphs etc are for all tokens avaliable need to make sol specific.

- [x] #45
- *Description for task 11*: The current ui and components used in the app are fckin ugly we need to improve it.
Few examples: 
Landing page:
<img width="1026" alt="Screenshot 2024-09-05 at 3 09 53 PM" src="https://github.com/user-attachments/assets/c2ed7be6-7efe-4923-a992-28032aaf5d76">
link: https://dribbble.com/shots/18097578-Ghost-Logo

Menu button inspirations:
<img width="579" alt="Screenshot 2024-09-05 at 3 10 20 PM" src="https://github.com/user-attachments/assets/186f79ac-2faf-40af-a5f9-0a7e5d9d710a">
link: https://dribbble.com/shots/19797491-Metaland-super-app-web-3-0

More:
https://dribbble.com/shots/19844186-OpenCord-Blockchain-Crypto-Web3-NFT-SocialFi-App

We need a full revamp.

- [ ] Task 13: *Add leaderboard and twitter linking stuff*
- *Description for task 13*: We need to add leaderboard to our app to distribute airdrops to people and also activity/twitter linking stuff to link to twitter (might change later)

- [x] Task 14: *UI stuff*
- *Description for task 13*: we have the worst ui ever need to improve it!!
---

- [ ] Task 15: *Deploy on expo*
- *Description for task 15*: Prod has problems with expo deployment
---

- [ ] #46
- *Description for task 16*: Chat only shows last 20 messages need to find a way to store old messages efficiently without calling durable objects again and again

### 📌 **Additional Notes**  
- DON'T BE A FAGGOT AND CRY WHY U CAN'T COMPLETE TASKS AND HOW YOU HAVE NEVER DONE IT BEFORE.
